### ISSUE TITLE
Login errors

### ISSUE THREAD

**Issue by tayyabbashir2224** [princ3od/Keepital#49]
I already have set-up for firebsse for login with google and facebook but it is not working i replaced the json file too, please public firrbsse config

**Comment by princ3od** [comment]
Hi @tayyabbashir2224,
Thanks for appreciating this project. 
Please also configure **Firebase Firestor**e and create one collection name `categories`, then add some documents following the image below.
Don't forget to enable Google provider in `Sign-in method` of **Firebase Authentication**.
![image](https://user-images.githubusercontent.com/17960926/147487927-85cd9481-d091-482d-9a89-b20f0b0c1de4.png)

But for testing the app, I suggest using the APK file.

**Comment by tayyabbashir2224** [comment]
actually my mobile does not support playstore when i run in debug mode it show playstore services missing error.  do you have any solution??

**Comment by tayyabbashir2224** [comment]
Exception has occurred.
PlatformException (PlatformException(firebase_firestore, com.google.firebase.firestore.FirebaseFirestoreException: Failed to get document because the client is offline., {code: unavailable, message: The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.}, null))

**Comment by princ3od** [comment]
Hi @tayyabbashir2224,
Did you enable `Firestore` in your **Firebase** project?

**Comment by tayyabbashir2224** [comment]
Ues, my hwawei phone not support google play servicesSent from my Huawei phone-------- Original message --------From: Trong Duong Binh ***@***.***>Date: Tue, Dec 28, 2021, 6:53 AMTo: princ3od/Keepital ***@***.***>Cc: Tayyab bashir ***@***.***>, Mention ***@***.***>Subject: Re: [princ3od/Keepital] Login errors (Issue #49)
Hi @tayyabbashir2224,
Did you enable Firestore in your Firebase project?

**Comment by princ3od** [comment]
Oh, I understand. I'm so sorry I can do anything about your problem since the problem comes from Huawei and Google. Flutter is created by Google, so I think Google Play Service might be a part of Flutter framework.

**Comment by tayyabbashir2224** [comment]
Some of flutter application are working in huaweiSent from my Huawei phone-------- Original message --------From: Trong Duong Binh ***@***.***>Date: Tue, Dec 28, 2021, 3:06 PMTo: princ3od/Keepital ***@***.***>Cc: Tayyab bashir ***@***.***>, Mention ***@***.***>Subject: Re: [princ3od/Keepital] Login errors (Issue #49)
Oh, I understand. I'm so sorry I can do anything about your problem since the problem comes from Huawei and Google. Flutter is created by Google, so I think Google Play Service might be a part of Flutter framework.
